name: sharedmobileutilities
description: A new Flutter package project.
version: 0.0.1
environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: '>=1.17.0'
dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.2.2
  rxdart: ^0.27.7
  crypto: ^3.0.2
  dio: ^4.0.6
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: null
