name: sharedmobileutilities
description: A new Flutter package project.
version: 0.0.1
environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: '>=1.17.0'
dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.2.1
  time_ago_provider: ^4.2.0
  path_provider: ^2.0.11
  fluttertoast: ^8.1.1
  url_launcher: ^6.1.6
  provider: ^6.0.4
  rxdart: ^0.27.5
  crypto: ^3.0.2
  get_it: ^7.2.0
  intl: ^0.17.0
  dio: ^4.0.6
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: null
